paths:
  output_root: "{project_root}/outputs/cross_dns5_to_vbd"
  tracking_root: "{project_root}/tracking/cross_dns5_to_vbd"
  project_root: "{project_root}"

dataset:
  dataset_type: "dns5"
  train_csv_16k: "/home/vali/Desktop/Disc-1TB/ULP-SE-aTENNuate/dataset/dns5-headset-16k/train.csv"
  test_csv_16k: "/home/vali/Desktop/Disc-1TB/ULP-SE-aTENNuate/dataset/voicebank-demand/16k/test.csv"
  test_csv: "/home/vali/Desktop/Disc-1TB/ULP-SE-aTENNuate/dataset/voicebank-demand/16k/test.csv"
  val_speakers: []
  rank_count: 0
